### ISSUE TITLE
Announcement: Textstat organisation

### ISSUE THREAD

**Issue by alxwrd** [textstat/textstat#167]
Hello! I am very pleased to announce the creation of the Textstat GitHub organisation: https://github.com/textstat.

I have been reviewing the current state of Textstat, and recently there has been a lot of interest in additional language support. We've accepted a number of contributions to add Spanish, German, Italian, and Arabic!

However, as more languages are getting added, the core of Textstat is becoming harder to maintain. With the addition of more languages, the base calculations are being pulled in more directions, some of which expect conflicting results.

With the introduction of the organisation, I am beginning the work to separate each language implementation into its own module. This will give each language the space to deviate from the core when applicable, but still be able to default back to solid base calculations.

Let me know your thoughts, either below, or via email: alxwrd@googlemail.com.

## Details

- My hope is to migrate `shivam5992/textstat` ➜ `textstat/textstat` _soon_.
- Contributions will still be accepted for the current implementation of Textstat. _Caveat: language additions (a new Spanish index, for example) will be migrated to their new repositories and may not be available straight away in the new version._
- The changes are planned with a version 1.0 release of Textstat.
- Until 1.0, there may still be releases for the current version.
  - _With 1.0, 0.x will become unsupported._
- I am not planning on maintaining backwards compatibility with the current API.
- Target Python version is currently planned at 3.8+.

## Planned architecture

The following diagram shows the planned "architecture" of Textstat.

<p align="center">
<img width="75%" src="https://user-images.githubusercontent.com/13941027/129884600-7e9b3537-6a0a-49cf-b7b6-d67e2113857c.png" alt="Diagram showing planned Textstat architecture. There is a user layer which is responsible for exposing the library API, and managing the CLI. A language layer which implements language specifics. Readability tests, any overrides to core functionality. And finally, a core layer which implements base text statistics. Character count, word count, etc.">
</p>

**Comment by LKirst** [comment]
Great idea! 

If there will be a language layer, we could try to use the CMU dictionary (imported from `nltk`) for the syllable count in the implementation for English because the CMU is more precise than the `pyphen` syllable count.

We could also use the migration to improve the documentation.

**Comment by GuillemGSubies** [comment]
Sounds good, maybe more details about the API would be interesting. Also it would be interesting to make texstat compatible with spacy Docs, so the generated analysis are extra properties of those objects

**Comment by alxwrd** [comment]
Wow 4 years has passed fast, and having kids is not conducive to working on open-source software it appears.

For those interested, there is an alpha version of [`v1.0.0`](https://github.com/orgs/textstat/discussions/211) available. Feedback welcome on the discussion, or reach out to me via the email on my profile.
