### ISSUE TITLE
Inconsistent result of `flesch_reading_ease()` between version `0.7.2` and `0.7.3`

### ISSUE THREAD

**Issue by XyLearningProgramming** [textstat/textstat#185]
Here's the steps to reproduce this issue using `docker`:
1. grab and run any docker image that has no python package pre-installed and have python>=3.6, for instance
```
 docker run -it refazul/python3.9.0 bash 
```
2. download `0.7.3`
```
root@9dbeec82e01e:/# pip3 freeze
root@9dbeec82e01e:/# pip3 install textstat==0.7.3
```
3. run commands below, test with a sentence
```
root@9dbeec82e01e:/# python3.9
Python 3.9.0 (default, Nov 11 2020, 20:23:31) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import textstat
>>> textstat.__version__
(0, 7, 2)
>>> textstat.flesch_reading_ease("\nSo now, Marne, our Chief Business Officer is going to take us through some of them. \nThanks, Mark. We'll see you in a minute! \nWhat if you could learn about anything in the world just by bringing it closer to you? \nSo, we're going to have an astrophysicist in the family. \nActually, I have to write this paper. Will you help me? \nLet's take a closer look. \nWhat part of the solar system are we talking about? \nSaturn. \nIf you were taking astrophysics, you could study in the Meta-Verse. \nDid you know the rings are made up of billions of icy particles? \nReally? \nLook at this. \nYou ready to do that paper now, right? \nYeah. \nIn the Meta-Verse, \nyou’ll be able to teleport not just to any place, but any time as well. Ancient Rome. Imagine standing on the streets, hearing the sounds, visiting the markets, to get a sense of the rhythm of life over 2,000 years ago. Imagine learning how the Forum was built by actually seeing the Forum get built, right in front of you.")
84.78
>>> exit()
```
5. download `0.7.2`
```
root@9dbeec82e01e:/# pip3 install textstat==0.7.2
```
7. run the same commands as step 3
```
root@9dbeec82e01e:/# python
Python 3.9.0 (default, Nov 11 2020, 20:23:31) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import textstat
>>> textstat.__version__
(0, 7, 2)
>>> textstat.flesch_reading_ease("\nSo now, Marne, our Chief Business Officer is going to take us through some of them. \nThanks, Mark. We'll see you in a minute! \nWhat if you could learn about anything in the world just by bringing it closer to you? \nSo, we're going to have an astrophysicist in the family. \nActually, I have to write this paper. Will you help me? \nLet's take a closer look. \nWhat part of the solar system are we talking about? \nSaturn. \nIf you were taking astrophysics, you could study in the Meta-Verse. \nDid you know the rings are made up of billions of icy particles? \nReally? \nLook at this. \nYou ready to do that paper now, right? \nYeah. \nIn the Meta-Verse, \nyou’ll be able to teleport not just to any place, but any time as well. Ancient Rome. Imagine standing on the streets, hearing the sounds, visiting the markets, to get a sense of the rhythm of life over 2,000 years ago. Imagine learning how the Forum was built by actually seeing the For)m get built, right in front of you.")   u
60.72
```
9. voila

Sorry for the long paragraph as the example. But it is that very text that produced this issue.
I am not very familiar with Flesch reading ease formula, but I still think such discrepancy is worth having another look.
Please enlighten me if I did something wrong or if you cannot reproduce this issue.

**Comment by LazyG** [comment]
I can confirm I'm also encountering this issue inside a docker container on 0.7.2.

**Comment by alxwrd** [comment]
Hi @XyLearningProgramming, thank you for raising this. Sorry I haven't had chance to investigate it yet.

Some changes between 0.7.2 and 0.7.3 that could be responsible for the change in score:
- Update syllable_count to use `.split()` and not `.split(' ')` so to split on all whitespace. https://github.com/shivam5992/textstat/pull/161
- Fix issue with `remove_punctuation()`. https://github.com/shivam5992/textstat/pull/172

**Comment by XyLearningProgramming** [comment]
Thanks for looking into this... So, to my understanding, there are some word-splitting & punctuation related changes possibly causing this issue. Since they are all "improved" towards performing the tasks in the intended way, can I say the reading ease score is more accurate, even though the score is different in different versions?
Also, feel free to close this issue if you investigate it and think this behavior is intended. Thank you again.

**Comment by alxwrd** [comment]
> the reading ease score is more accurate

That's correct. As we make these changes, the hope is we're moving towards more accurate scores.

I'll close this issue, but if you find something wrong, feel free to open it or raise a new one.
