### ISSUE TITLE
[Bug]: 0.7.4 is not on Pypi

### ISSUE THREAD

**Issue by AieatAssam** [textstat/textstat#200]
### Operating system

Linux

### Download source

PyPi

### Python distribution

CPython

### Python version

Python 3.12

### What happened?

PyPi index only contains package versions up to 0.7.3, so the only way currently to have 3.12 compatibility is by manually installing setuptools (and suffer pkg_resources deprecation warning) or by installing from source.

### Other information

Potentially failed push to PyPi?

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/textstat/community/blob/main/CODE_OF_CONDUCT.md)

**Comment by alxwrd** [comment]
Whoops! Apologies - I've just built and pushed 0.7.4 to PyPi: https://pypi.org/project/textstat/0.7.4/
